/*
 * interfaz.java
 *
 * Created on 17-jun-2009, 16:19:00
 */

package cf.gui;

import java.awt.AlphaComposite;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import javax.swing.JOptionPane;
/*import cf.matrizCasillas.logica.ControladorMatrizColores;
import cf.matrizCasillas.logica.MatrizColores;
import cf.matrizCasillas.logica.ObservadorMatrizColores;*/


/**
 *
 * @author luigi
 */
public class interfaz extends javax.swing.JFrame implements ObservadorMatrizColores {



    /*************************** Variables de MemoCasillas************************/
    private MatrizColores matrizColores;
    private Rectangle2D rectangulos [][];
    private float tamanioBase;
    private float tamanioAltura;
    private ControladorMatrizColores controladorMatrizColores;



    /** Creates new form interfaz */
    public interfaz() {
        initComponents();
        this.setTitle("Casino Fantasma");


      //  jPanel9.paint(dameGraficos(jPanel9.getGraphics()));
        String tamanio [] = {"2","3","4","5","6","7","8","9","10"};
        numCasillasBox.setModel(new javax.swing.DefaultComboBoxModel(tamanio));
        matrizColores = new MatrizColores(new cf.matrizCasillas.util.Dimension(5,5));

        // Cambia esto.
        numColoresBox.setModel(new javax.swing.DefaultComboBoxModel(tamanio));

          
    }

    /************************* Metodos de MemoCasillas***************************/

   public void pinta (Graphics g) {

      try {
  Graphics2D g2 = (Graphics2D)g;
  AlphaComposite ac;
  rectangulos = new Rectangle2D[matrizColores.getColumnas()][matrizColores.getFilas()];

  Dimension dim = jPanel9.getSize();
  tamanioBase = (float) (dim.getWidth() / matrizColores.getColumnas());
  tamanioAltura = (float) (dim.getHeight() / matrizColores.getFilas());
 int puntoMedioX,puntoMedioY;
  for (int i = 0; i < matrizColores.getFilas(); i++){
      for (int j = 0; j < matrizColores.getColumnas();j++){

        rectangulos[j][i] =  new Rectangle2D.Float(j * tamanioBase,i * tamanioAltura,tamanioBase,tamanioAltura);
        ac = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f);
        g2.setColor(matrizColores.getCasilla(j,i));
      //  g2.setComposite(ac);
        g2.fill(rectangulos[j][i]);
      }

  }
      }
      catch (Exception ex){
          System.out.println("Exception en pinta");
      }
}


    public void pinta8Puzzle (Graphics g) {

      try {
  Graphics2D g2 = (Graphics2D)g;
  AlphaComposite ac;
  rectangulos = new Rectangle2D[matrizColores.getColumnas()][matrizColores.getFilas()];

  Dimension dim = jPanel9.getSize();
  tamanioBase = (float) (dim.getWidth() / matrizColores.getColumnas());
  tamanioAltura = (float) (dim.getHeight() / matrizColores.getFilas());
 float puntoMedioX,puntoMedioY;
  for (int i = 0; i < matrizColores.getFilas(); i++){
      for (int j = 0; j < matrizColores.getColumnas();j++){

        rectangulos[j][i] =  new Rectangle2D.Float(j * tamanioBase,i * tamanioAltura,tamanioBase,tamanioAltura);
        ac = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f);
        g2.setColor(matrizColores.getCasilla(j,i));
      //  g2.setComposite(ac);
        g2.fill(rectangulos[j][i]);
        puntoMedioX = j * tamanioBase + tamanioBase/2;
        puntoMedioY = i * tamanioAltura + tamanioAltura/2;
        g2.drawString("CX:"+i+"CY:"+j,puntoMedioY,puntoMedioX);
      //  g2.drawString("adios",puntoMedioX*2, puntoMedioY*2);
      }

  }
      }
      catch (Exception ex){
          System.out.println("Exception en pinta");
      }
}


   

   public void setControladorMatrizColores(ControladorMatrizColores controladorMatrizColores) {
        this.controladorMatrizColores = controladorMatrizColores;
    }

    public void movimientoRealizado(MatrizColores matriz) {

             matrizColores = matriz;
            pinta(jPanel9.getGraphics());
            pinta8Puzzle(jPanel10.getGraphics());
    }
  
    public void partidaTerminada(boolean acierto) {

        if (acierto)
              JOptionPane.showMessageDialog(null,"Has acertado", "Resultado",JOptionPane.INFORMATION_MESSAGE);
        else   JOptionPane.showMessageDialog(null,"Has fallado", "Resultado",JOptionPane.INFORMATION_MESSAGE);
    }



    /****************************************************************************/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        numColoresBox = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        numCasillasBox = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Comprobar casillero");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel9.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel9MouseReleased(evt);
            }
        });
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel9MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        numColoresBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel23.setText("Tamaño casilla");

        jButton2.setText("Comenzar la partida");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        numCasillasBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel24.setText("Num colores");

        jPanel10.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel10MouseReleased(evt);
            }
        });
        jPanel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel10MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Cargar fichero");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(numCasillasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(numColoresBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(numCasillasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numColoresBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton4)))
                .addGap(198, 198, 198))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseMoved


        // Este método te va a venir bien para informar del juego que se va a ejecutar?

    //    jLabel22.setText(Integer.toString(evt.getX()) + " " + Integer.toString(evt.getY()));
        //pinta(jPanel9.getGraphics());
       // jPanel9.setBackground(Color.BLACK);
        //jPanel9.paint(jPanel9.getGraphics());
       
        //jPanel9.setIgnoreRepaint(rootPaneCheckingEnabled)
    }//GEN-LAST:event_jPanel9MouseMoved

    private void jPanel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseReleased

       /*  try {
        jLabel22.setText(Integer.toString(evt.getX()) + " " + Integer.toString(evt.getY()));

         int i = (int) (evt.getX() / tamanioBase);
         int j = (int) (evt.getY() / tamanioAltura);

        /* colores colorines = new colores();
         casillasColor [i][j]= colorines.dameSiguienteColor(casillasColor [i][j]);*/

        // controladorMatrizColores.insertarMovimiento(new Posicion(i,j));
        // casillasColor [i][j]= Color.getColor(colorin);//colores.getColor(colorines.toString());
                 pinta(jPanel9.getGraphics());
 
        pinta8Puzzle(jPanel10.getGraphics());
       /*  }
         catch (Exception ex){
             System.out.println("Te has salido?");
         }*/
    }//GEN-LAST:event_jPanel9MouseReleased




    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

       //   controladorMatrizColores.iniciarPartida(50);//Integer.parseInt(numCasillasBox.getSelectedItem().toString()));

        controladorMatrizColores.iniciarPartida(Integer.parseInt(numCasillasBox.getSelectedItem().toString()),Integer.parseInt(numColoresBox.getSelectedItem().toString()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        controladorMatrizColores.verificarPartida();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        controladorMatrizColores.comenzarPartida();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPanel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseReleased

    private void jPanel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseMoved



   public void partidaEmpezada(MatrizColores matrizColores) {
           this.matrizColores = matrizColores;
           pinta(jPanel9.getGraphics());
           pinta8Puzzle(jPanel10.getGraphics());
    }

     @Override
    public void repaint(){
        super.repaint();
        jPanel9.repaint();
        jPanel10.repaint();


    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JComboBox numCasillasBox;
    private javax.swing.JComboBox numColoresBox;
    // End of variables declaration//GEN-END:variables


}
