package cf.gui;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import javax.swing.JOptionPane;
import cf.logica.ControladorCasinoFantasma;
import cf.logica.Movimientos;
import cf.logica.ObservadorCasinoFantasma;

import cf.logica.TableroCasillas;
import cf.logica.TipoBusquedas;
import java.awt.Rectangle;
import javax.swing.JFileChooser;
import javax.swing.JPanel;


/**
 *
 * @author luigi
 */
public class interfaz extends javax.swing.JFrame implements ObservadorCasinoFantasma {



    /*************************** Variables de MemoCasillas************************/
    //private TableroCasillas matrizColores;
    private Rectangle2D rectangulos [][];
    private float tamanioBase;
    private float tamanioAltura;
    private ControladorCasinoFantasma controladorCasino;
    TableroCasillas matriz;


    /** Creates new form interfaz */
    public interfaz() {
        initComponents();
        this.setTitle("Casino Fantasma");
          Dimension dim = getToolkit().getScreenSize();
        Rectangle abounds = getBounds();
        setLocation((dim.width - abounds.width) / 2,
      (dim.height - abounds.height) / 2);
      //matrizColores = new TableroCasillas(new cf.util.Dimension(5,5));
        
        String busquedas[] = new String[TipoBusquedas.values().length];
        for (int i = 0; i < TipoBusquedas.values().length;i++)
            busquedas[i] = TipoBusquedas.values()[i].toString();
     jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(busquedas));


    }

   public void setControladorCasino(ControladorCasinoFantasma controladorMatrizColores) {
        this.controladorCasino = controladorMatrizColores;
    }

    public void partidaTerminada() {


         JOptionPane.showMessageDialog(this,"Partida finalizada");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel9.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel9MouseReleased(evt);
            }
        });
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel9MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jButton2.setText("Comenzar la partida");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Situación del jugador");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel6.setText("Informacion del mini-juego:");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 10));
        jLabel8.setText("Situa el ratón sobre una de las zonas para saber la estrategia y el juego:");

        jLabel10.setText("Nombre de la estrategia:");

        jLabel7.setText("Nombre del juego:");

        jLabel11.setText(" ");

        jLabel12.setText("Valor apuesta:");

        jLabel13.setText(".");

        jLabel4.setText("Vidas acumuladas por el jugador:");

        jLabel5.setText(".");

        jLabel1.setText("Al cerrar el casino se puede guardar un fichero log con las trazas del programa.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addContainerGap(134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addGap(43, 43, 43)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(215, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addContainerGap(291, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Método de búsqueda del casino:");

        jLabel15.setText("Segundos a esperar entre juego y juego:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "5", "10", "20", "30", "40", "50", "60", " " }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Cargar fichero XML");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addComponent(jComboBox1, 0, 209, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(609, 609, 609)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(1, 1, 1)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseMoved


        //Tenemos que calcular las coordenadas exactas... */

        /// como siempre seran 10 las coordenadas del casino...
        if (matriz != null){
        int posX = evt.getX() / (jPanel9.getWidth() / matriz.getColumnas()); // dividido entre el tamaño del cuadrado.
        int posY = evt.getY() / (jPanel9.getHeight() / matriz.getFilas());

            controladorCasino.dameNombreJuegoYEstrategia(posX,posY);

        // Este método te va a venir bien para informar del juego que se va a ejecutar?

    //      jLabel7.setText(Integer.toString(evt.getX()) + " " + Integer.toString(evt.getY()));

            System.out.println("La coordenada X es " + posX + "y la coordenada Y es " + posY);
        }
        //pinta(jPanel9.getGraphics());
       // jPanel9.setBackground(Color.BLACK);
        //jPanel9.paint(jPanel9.getGraphics());
       
        //jPanel9.setIgnoreRepaint(rootPaneCheckingEnabled)
    }//GEN-LAST:event_jPanel9MouseMoved

    public void muestraInformacionCasilla(String nombreJuego,String nombreBusqueda,int valorApuesta){

        jLabel9.setText(nombreJuego);
        jLabel11.setText(nombreBusqueda);
        jLabel13.setText(" " + valorApuesta);

        System.out.println(nombreJuego);
        System.out.println(nombreBusqueda);
        System.out.println(" " + valorApuesta);
    }


    private void jPanel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseReleased

       /*  try {
        jLabel22.setText(Integer.toString(evt.getX()) + " " + Integer.toString(evt.getY()));

         int i = (int) (evt.getX() / tamanioBase);
         int j = (int) (evt.getY() / tamanioAltura);

        /* colores colorines = new colores();
         casillasColor [i][j]= colorines.dameSiguienteColor(casillasColor [i][j]);*/

        // controladorMatrizColores.insertarMovimiento(new Posicion(i,j));
        // casillasColor [i][j]= Color.getColor(colorin);//colores.getColor(colorines.toString());
                // pinta(jPanel9.getGraphics());
 
//        pintaMiniJuego(jPanel10.getGraphics());
       /*  }
         catch (Exception ex){
             System.out.println("Te has salido?");
         }*/
    }//GEN-LAST:event_jPanel9MouseReleased




    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        controladorCasino.comenzarPartida(TipoBusquedas.valueOf(jComboBox1.getSelectedItem().toString()));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed



    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFileChooser chooser = new JFileChooser();
        ExampleFileFilter filter = new ExampleFileFilter() {};
        filter.addExtension("xml");
        filter.setDescription("Ficheros XML(*.xml)");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {

            controladorCasino.abrirFichero(chooser.getSelectedFile().toString());
           /* control.abrirBaseDeDatos(chooser.getSelectedFile().toString());
            System.out.println("You chose to open this file: " +
                    chooser.getSelectedFile().getName());*/
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        controladorCasino.salir();
    }//GEN-LAST:event_formWindowClosing

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

        controladorCasino.setearVelocidad(Integer.parseInt(jComboBox2.getSelectedItem().toString()));
    }//GEN-LAST:event_jComboBox2ItemStateChanged



   public void partidaEmpezada(TableroCasillas matrizColores) {
          // this.matrizColores = matrizColores;
           //pinta(jPanel9.getGraphics());
           //pintaMiniJuego(jPanel10.getGraphics());
    }

     @Override
    public void repaint(){
        super.repaint();
        jPanel9.repaint();
       // jPanel10.repaint();


    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void actualizarJuego(TableroCasillas matriz) {

        /*matrizColores = matriz;
        pinta(jPanel9.getGraphics());*/
        this.matriz = matriz;
        dibujarMatrizColores(jPanel9, matriz);
        dibujarRejilla(jPanel9, matriz);
        


    }

    public void actualizarMiniJuego(TableroCasillas matriz) {

         /*matrizColores = matriz;
         mostrarLaberinto();*/
         //pinta(jPanel10.getGraphics());
        // dibujarMatrizColores(jPanel10, matriz);
    }

    public void partidaEmpezada(Color[][] matriz) {
       jButton2.setEnabled(false);
    }

    public void movimientoRealizado(Color[][] matriz) {
       
    }

    public void mostrarVidas(int vidas){

        jLabel5.setText(" " + vidas);
    }



    /****************************************************************************************
     *                       Métodos de dibujo e información de los mini-juegos
     ****************************************************************************************/

    public void mostrarInfoJuego(String info){

        jTextArea1.append(info + "\n");
        
    }


    public void reseteaInfoJuego(){

        jTextArea1.setText("");

    }

    public void dibujarRejilla(JPanel jPanel,TableroCasillas matriz){

        Graphics2D g2 = (Graphics2D)jPanel.getGraphics();
        Dimension dim = jPanel.getSize();
          tamanioBase = (float) (dim.getWidth() / matriz.getColumnas());
          tamanioAltura = (float) (dim.getHeight() / matriz.getFilas());


         int espacio = dim.height/matriz.getColumnas();
         for (int i = 0; i < dim.getHeight();i= i + espacio){
              g2.setColor(Color.BLACK);
              g2.drawLine(0,i,dim.height,i);
         }
         espacio = dim.height/matriz.getColumnas();
         for (int i = 0; i < dim.getWidth();i= i + espacio){
              g2.setColor(Color.BLACK);
              g2.drawLine(i,0,i,dim.width);

         }
}

    
    public void dibujarMatrizColores(JPanel jPanel,TableroCasillas matriz){

      try {
          Graphics2D g2 = (Graphics2D)jPanel.getGraphics();
          AlphaComposite ac;
          rectangulos = new Rectangle2D[matriz.getColumnas()][matriz.getFilas()];

          Dimension dim = jPanel.getSize();
          tamanioBase = (float) (dim.getWidth() / matriz.getColumnas());
          tamanioAltura = (float) (dim.getHeight() / matriz.getFilas());

          for (int i = 0; i < matriz.getFilas(); i++)
              for (int j = 0; j < matriz.getColumnas();j++){
                rectangulos[j][i] =  new Rectangle2D.Float(j * tamanioBase,i * tamanioAltura,tamanioBase,tamanioAltura);
                ac = AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f);
                g2.setColor(matriz.getColorCasilla(j,i));
                g2.fill(rectangulos[j][i]);
              }
      }
      catch (Exception ex){
          System.out.println("Exception en dibuja MatrizColores");
     }
    }

    public void muestraInfo(String informacionError) {

        JOptionPane.showMessageDialog(this,informacionError);
    }

    public void muestraVidasJugador(int vidas) {

        jLabel5.setText(" " + vidas);
    }
}
